eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888
spring:
  application:
    name: geo-spring-websocket
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1