eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.88.200:8761/eureka/
server:
  port: 8899
spring:
  application:
    name: geo-spring
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1